// 費波那契數列
// var array1 = prompt("num", 2);
// var num = Number(array1);
// var sums = fib(num);
// alert(sums);

// function fib(n) {
//     const result = [0, 1];

//     for (let index = 2; index <= n; index++) {
//         // 倒數第一個數
//         const a = result[index - 1]; // or result[result.length -1]

//         // 倒數第二個數
//         const b = result[index - 2];

//         result.push(a + b);
//     }
//     return result[result.length - 1];
// }